development:
  host: dpk.local
  api_key: n3eh0gagikpys3bjapuiz5gudqvc60

qa:
  host: qa.digitaleprodukter.dk
  username: jeppe
  password: 1UMTpIdlgJki8ToL
  api_key: n3eh0gagikpys3bjapuiz5gudqvc60

production:
  host: www.digitaleprodukter.dk
  api_key: n3eh0gagikpys3bjapuiz5gudqvc60
