development:
  adapter: mysql
  host: localhost
  database: bygviden_development
  username: root

qa:
  adapter: mysql
  host: db02
  database: bygviden_qa
  username: bygviden_qa
  password: secret

production:
  adapter: mysql
  host: db02
  database: bygviden_production
  username: bygviden_prod
  password: secret
